name: Automatic build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v2

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install libfuse-dev liblzo2-dev meson ninja-build autopoint po4a
        git clone https://github.com/mgord9518/libfuse
        git clone https://github.com/ebiggers/libdeflate
        git clone https://github.com/facebook/zstd
        git clone https://github.com/lz4/lz4
        git clone https://github.com/xz-mirror/xz

    # TODO: do this in build.zig
    - name: Build FUSE3
      run: |
        cd libfuse
        mkdir build
        cd build
        meson ..
        meson configure -Ddefault_library=static -Dbuildtype=release
        ninja
        cd ../../

    - name: Build XZ
      run: |
        cd xz
        ./autogen.sh
        ./configure --disable-xz --disable-doc
        make CFLAGS='-O3'

    - name: Build (x86_64)
      run: |
        # ZLIB
        zig build -Doptimize=ReleaseFast -Dcpu=x86_64 -Denable-zlib=true -Duse-libdeflate=true -Denable-zstd=false -Denable-lz4=false -Denable-xz=false -Denable-lzo=false -Duse-system-fuse=false
        strip zig-out/bin/squashfuse
        mv zig-out/bin/squashfuse squashfuse_zlib.x86_64

        # ZSTD
        zig build -Doptimize=ReleaseFast -Dcpu=x86_64 -Denable-zlib=false -Denable-zstd=true -Denable-lz4=false -Denable-xz=false -Denable-lzo=false -Duse-system-fuse=false
        strip zig-out/bin/squashfuse
        mv zig-out/bin/squashfuse squashfuse_zlib.x86_64

        # LZ4
        zig build -Doptimize=ReleaseFast -Dcpu=x86_64 -Denable-zlib=false -Denable-zstd=false -Denable-lz4=true -Denable-xz=false -Denable-lzo=false -Duse-system-fuse=false
        strip zig-out/bin/squashfuse
        mv zig-out/bin/squashfuse squashfuse_zlib.x86_64
        
        # XZ
        zig build -Doptimize=ReleaseFast -Dcpu=x86_64 -Denable-zlib=false -Denable-zstd=false -Denable-lz4=false -Denable-xz=true -Denable-lzo=false -Duse-system-fuse=false
        strip zig-out/bin/squashfuse
        mv zig-out/bin/squashfuse squashfuse_zlib.x86_64

# TODO: write and add tests
#    - name: Test build
#      run:

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: |
          squashfuse_*
#          *.AppImage
#          *.shImg
#          *.zsync
