name: Automatic build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v2

    - name: Build (Musl libc, static, x86_64)
      run: ARCH=x86_64 OS=linux LIBC=musl ./build.sh

    - name: Build (GLibC 2.16, x86_64)
      run: ARCH=x86_64 OS=linux LIBC=gnu.2.16 ./build.sh

    - name: Test
      run: |
        zig build test
        zig build test -Dtarget=x86_64-linux-gnu.2.16 -Doptimize=ReleaseSafe
        zig build test -Dtarget=x86_64-linux-gnu.2.16 -Doptimize=ReleaseFast
        zig build test -Dtarget=x86_64-linux-gnu.2.16 -Doptimize=ReleaseSmall

        zig build test
        zig build test -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSafe
        zig build test -Dtarget=x86_64-linux-musl -Doptimize=ReleaseFast
        zig build test -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSmall

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: |
          squashfuse*
