name: Automatic build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install squashfs-tools zip

    - name: Build (Linux, Musl libc, static, x86_64)
      run: ARCH=x86_64 OS=linux LIBC=musl ./build.sh

    - name: Build (Linux, Musl libc, static, aarch64)
      run: ARCH=aarch64 OS=linux LIBC=musl ./build.sh

    - name: Build (Linux, Musl libc, static, x86)
      run: ARCH=x86 OS=linux LIBC=musl ./build.sh

    - name: Build (Linux, Musl libc, static, arm)
      run: ARCH=arm OS=linux LIBC=musleabi ./build.sh

    - name: Build (Linux, Musl libc, static, riscv64)
      run: ARCH=riscv64 OS=linux LIBC=musl ./build.sh

    # TODO: support Windows FUSE through WinFSP
    - name: Build (Windows, GLibC, x86_64, no FUSE)
      run: ARCH=x86_64 OS=windows LIBC=gnu ./build.sh

    - name: Build (Windows, GLibC, aarch64, no FUSE)
      run: ARCH=aarch64 OS=windows LIBC=gnu ./build.sh

    - name: Build (Windows, GLibC, x86, no FUSE)
      run: ARCH=x86 OS=windows LIBC=gnu ./build.sh

    # TODO: macOS

    - name: Test
      run: |
        zig build test
        zig build test -Dtarget=x86_64-linux-gnu -Doptimize=ReleaseSafe
        zig build test -Dtarget=x86_64-linux-gnu -Doptimize=ReleaseFast
        zig build test -Dtarget=x86_64-linux-gnu -Doptimize=ReleaseSmall

        zig build test
        zig build test -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSafe
        zig build test -Dtarget=x86_64-linux-musl -Doptimize=ReleaseFast
        zig build test -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSmall

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: |
          squashfuse*
