name: Automatic build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v2

    - name: Install squashfs-tools
      run: |
        sudo apt update
        sudo apt install squashfs-tools

      # TODO: possibly remove GLibC? I'll have to do some testing and see if
      # there are any large benefits to keeping it, because it's now only being
      # used for the compression libraries
    - name: Build (Musl libc, static, x86_64)
      run: ARCH=x86_64 OS=linux LIBC=musl ./build.sh

    - name: Build (GLibC 2.16, x86_64)
      run: ARCH=x86_64 OS=linux LIBC=gnu.2.16 ./build.sh

    - name: Build (Musl libc, static, aarch64)
      run: ARCH=aarch64 OS=linux LIBC=musl ./build.sh

    - name: Build (GLibC 2.17, aarch64)
      run: ARCH=aarch64 OS=linux LIBC=gnu.2.17 ./build.sh

    - name: Build (Musl libc, static, x86)
      run: ARCH=x86 OS=linux LIBC=musl ./build.sh

    - name: Build (GLibC 2.16, x86)
      run: ARCH=x86 OS=linux LIBC=gnu.2.16 ./build.sh

    - name: Build (Musl libc, static, arm)
      run: ARCH=arm OS=linux LIBC=musleabi ./build.sh

    - name: Build (GLibC 2.16, arm)
      run: ARCH=arm OS=linux LIBC=gnueabi.2.16 ./build.sh

    - name: Build (Musl libc, static, riscv64)
      run: ARCH=riscv64 OS=linux LIBC=musl ./build.sh

        # TODO: riscv64 GLibC and riscv32
        #    - name: Build (GLibC 2.16, riscv64)
        #      run: ARCH=riscv64 OS=linux LIBC=gnu.2.16 ./build.sh

    - name: Build test images
      run: |
        cd test
        ./make_images.sh
        cd ..

    - name: Test
      run: |
        zig build test
        zig build test -Dtarget=x86_64-linux-gnu.2.16 -Doptimize=ReleaseSafe
        zig build test -Dtarget=x86_64-linux-gnu.2.16 -Doptimize=ReleaseFast
        zig build test -Dtarget=x86_64-linux-gnu.2.16 -Doptimize=ReleaseSmall

        zig build test
        zig build test -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSafe
        zig build test -Dtarget=x86_64-linux-musl -Doptimize=ReleaseFast
        zig build test -Dtarget=x86_64-linux-musl -Doptimize=ReleaseSmall

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: |
          squashfuse*
